from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import sounderpy as spy
from metpy.calc import wind_components
from metpy.units import units


WORK_DIR = Path(os.getenv("WORK_DIR", "/data/work"))
OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", "/data/output"))
WEB_IMAGES_DIR = Path(os.getenv("WEB_IMAGES_DIR", "/data/web/images"))
WEB_SHARPY_DIR = Path(os.getenv("WEB_SHARPY_DIR", "/data/web/sharpy"))
MANIFEST_PATH = Path(os.getenv("MANIFEST_PATH", "/data/web/manifest.json"))
SHARPY_NAME_RE = re.compile(r"SHARP+Y\.txt$", re.IGNORECASE)


@dataclass
class ProcessResult:
    source: Path
    image_name: str
    sharpy_name: str
    created: bool


def _safe_name(relative_path: Path) -> str:
    stem = relative_path.name
    if stem.lower().endswith(".txt"):
        stem = stem[:-4]
    flattened = f"{relative_path.parent.as_posix()}__{stem}" if relative_path.parent.as_posix() != "." else stem
    flattened = re.sub(r"[^A-Za-z0-9_.-]+", "_", flattened)
    return flattened


def _parse_sharpy(path: Path) -> dict:
    lines = path.read_text(errors="ignore").splitlines()

    data_started = False
    rows: list[list[float]] = []
    for raw in lines:
        line = raw.strip()
        if not line:
            continue
        if line.startswith("%RAW%"):
            data_started = True
            continue
        if not data_started:
            continue
        if line.startswith("%END%"):
            break

        parts = [p.strip() for p in line.split(",")]
        if len(parts) < 6:
            continue

        try:
            values = [float(parts[i]) for i in range(6)]
        except ValueError:
            continue

        if values[0] <= 0:
            continue
        rows.append(values)

    if len(rows) < 5:
        raise ValueError(f"Not enough valid sounding levels in {path}")

    arr = np.array(rows)
    pres = arr[:, 0] * units.hectopascal
    hght = arr[:, 1] * units.meter
    temp = arr[:, 2] * units.degC
    dwpt = arr[:, 3] * units.degC
    wdir = arr[:, 4] * units.degree
    wspd = arr[:, 5] * units.knots

    u_wind, v_wind = wind_components(wspd, wdir)

    clean_data = {
        "T": temp,
        "Td": dwpt,
        "z": hght,
        "p": pres,
        "u": u_wind,
        "v": v_wind,
        "site_info": {
            "site-id": "FILE",
            "site-name": path.stem,
            "site-latlon": [0.0, 0.0],
            "site-elv": float(hght.m[0]),
            "source": "SHARPY",
            "model": "FILE",
            "fcst-hour": "F000",
            "run-time": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%MZ"),
            "valid-time": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%MZ"),
            "box_area": "",
        },
        "titles": {
            "top_title": "SkewT from SHARPY file",
            "left_title": path.stem,
            "right_title": "Generated by sounderpy",
        },
    }

    return clean_data


def _plot_to_png(clean_data: dict, out_png: Path) -> None:
    out_png.parent.mkdir(parents=True, exist_ok=True)

    plot = spy.build_sounding(clean_data, color_blind=True, dark_mode=False, save=False)
    if hasattr(plot, "savefig"):
        plot.savefig(out_png, dpi=160, bbox_inches="tight")
        try:
            import matplotlib.pyplot as plt

            plt.close("all")
        except Exception:
            pass
        return

    # Fallback for APIs that only save by base filename.
    base = out_png.with_suffix("")
    spy.build_sounding(clean_data, color_blind=True, dark_mode=False, save=True, filename=str(base))


def _manifest_entry(source: Path, image_name: str, sharpy_name: str) -> dict:
    image_path = WEB_IMAGES_DIR / image_name
    mtime = image_path.stat().st_mtime if image_path.exists() else source.stat().st_mtime
    return {
        "id": image_name.removesuffix(".png"),
        "image": f"images/{image_name}",
        "sharpy": f"sharpy/{sharpy_name}",
        "source": str(source),
        "updated_unix": mtime,
        "updated_iso": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
    }


def process_one(source: Path) -> ProcessResult:
    rel = source.relative_to(WORK_DIR)
    name = _safe_name(rel)
    image_name = f"{name}.png"
    sharpy_name = f"{name}.txt"

    out_png = OUTPUT_DIR / image_name
    web_png = WEB_IMAGES_DIR / image_name
    web_txt = WEB_SHARPY_DIR / sharpy_name

    created = False
    if not out_png.exists():
        clean_data = _parse_sharpy(source)
        _plot_to_png(clean_data, out_png)
        created = True

    web_png.parent.mkdir(parents=True, exist_ok=True)
    web_txt.parent.mkdir(parents=True, exist_ok=True)

    if not web_png.exists() or out_png.stat().st_mtime > web_png.stat().st_mtime:
        shutil.copy2(out_png, web_png)
    if not web_txt.exists() or source.stat().st_mtime > web_txt.stat().st_mtime:
        shutil.copy2(source, web_txt)

    return ProcessResult(source=source, image_name=image_name, sharpy_name=sharpy_name, created=created)


def write_manifest(entries: list[dict]) -> None:
    payload = {
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "count": len(entries),
        "items": sorted(entries, key=lambda x: x["updated_unix"], reverse=True),
    }
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(payload, indent=2))


def run() -> int:
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    WEB_IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    WEB_SHARPY_DIR.mkdir(parents=True, exist_ok=True)

    files = sorted(
        p for p in WORK_DIR.rglob("*.txt") if p.is_file() and SHARPY_NAME_RE.search(p.name)
    )
    entries: list[dict] = []

    for src in files:
        if not src.is_file():
            continue
        try:
            result = process_one(src)
            entries.append(_manifest_entry(result.source, result.image_name, result.sharpy_name))
            state = "created" if result.created else "skipped"
            print(f"[{state}] {src}")
        except Exception as exc:
            print(f"[error] {src}: {exc}")

    write_manifest(entries)
    print(f"Processed {len(files)} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
